[JBTM-3978] Migrating Jenkins CI to GitHub Actions

diff --git a/.github/workflows/as_tests-test.yml b/.github/workflows/as_tests-test.yml
--- a/.github/workflows/as_tests-test.yml
+++ b/.github/workflows/as_tests-test.yml
@@ -1,4 +1,4 @@
-name: CORE
+name: AS_TESTS
 
 on:
   push:
@@ -9,24 +9,24 @@ on:
     types:
       - completed
   workflow_dispatch:
-    
+
 # Only run the latest job
 concurrency:
   group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
   cancel-in-progress: true
 
 jobs:
-  core-test:
+  as_tests-test:
     strategy:
       matrix:
         java-version: [ 17 ]
-    name: CORE test with JDK ${{ matrix.java-version }}
+    name: AS_TESTS test with JDK ${{ matrix.java-version }}
     timeout-minutes: 120
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
 
-      - name: Check for `testing/core` label
+      - name: Check for `testing/as_tests` label
         id: check-label
         run: |
           echo "should_skip=false" >> $GITHUB_OUTPUT
@@ -34,8 +34,8 @@ jobs:
             echo "Checking labels on PR #${{ github.event.pull_request.number }}..."
             LABELS=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
             echo "Labels found: $LABELS"
-            if ! echo "$LABELS" | grep -q "^testing/core$"; then
-              echo "Label 'testing/core' not found. Skipping job."
+            if ! echo "$LABELS" | grep -q "^testing/rts$"; then
+              echo "Label 'testing/as_tests' not found. Skipping job."
               echo "should_skip=true" >> $GITHUB_OUTPUT
             fi
           fi
@@ -61,22 +61,25 @@ jobs:
           restore-keys: |
             maven-${{ runner.os }}-
 
-      - name: CORE testing profile
+      - name: AS_TESTS testing profile
         if: steps.check-label.outputs.should_skip != 'true'
         run: |
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git config --global user.name "github-actions[bot]"  
-          WORKSPACE=$PWD PROFILE=CORE ./scripts/hudson/narayana.sh
+          WORKSPACE=$PWD PROFILE=AS_TESTS ./scripts/hudson/narayana.sh
 
       - uses: actions/upload-artifact@v4
         if: steps.check-label.outputs.should_skip != 'true' && always()
         with:
-          name: core-logs-jdk${{ matrix.java-version }}
+          name: as_tests-logs-jdk${{ matrix.java-version }}
           path: |
             **/*.*log*
-            **/ObjectStore*/**
+            **/ObjectStore*/**  
             **/tx-object-store/**
             **/*tx-object-store.zip
             **/target/*surefire-reports*/**
             **/target/*failsafe-reports*/**
+            jboss-as/build/target/wildfly-*/**
+            jboss-as/dist/target/wildfly-*.zip
+            jboss-as/dist/target/wildfly-*/standalone/log/
           if-no-files-found: error
